/**
 * Visual Creative Choice System — developer-seeded starter packs (PR #710)
 *
 * These are product-level visual helpers, not a closed whitelist.
 * Free-text camera / performance / action fields remain fully usable.
 *
 * Mapping rules:
 * - camera family  → ShotCamera (shotSize / angle / movement / composition)
 * - lighting family → ShotCamera.lighting (and promptFragment)
 * - expression     → ShotPerformance.emotion
 * - action         → shot.action free-text
 * - style          → styleHint + promptFragment (prompt-level for v1)
 */
import type { VisualChoiceManifest, VisualChoicePreset } from "./visualChoiceTypes";
import { VISUAL_CHOICE_MANIFEST_VERSION } from "./visualChoiceTypes";

const actionPresets: VisualChoicePreset[] = [
  {
    id: "action.standing",
    family: "action",
    label: "站立",
    description: "自然站姿",
    preview: "🧍",
    promptFragment: "standing naturally, relaxed posture",
    structured: { action: "站立，自然姿態" },
    tags: ["靜態", "基礎"],
  },
  {
    id: "action.walking",
    family: "action",
    label: "行走",
    description: "向前走",
    preview: "🚶",
    promptFragment: "walking forward at a natural pace",
    structured: { action: "向前行走" },
    tags: ["動態"],
  },
  {
    id: "action.running",
    family: "action",
    label: "奔跑",
    description: "快速跑動",
    preview: "🏃",
    promptFragment: "running quickly, dynamic motion",
    structured: { action: "奔跑" },
    tags: ["動態", "激烈"],
  },
  {
    id: "action.looking_back",
    family: "action",
    label: "回頭望",
    description: "身體仍向前、頭部回望",
    preview: "↩️",
    promptFragment: "looking back over the shoulder while body faces forward",
    structured: { action: "回頭望，身體仍朝前" },
    tags: ["情緒", "轉折"],
  },
  {
    id: "action.pointing",
    family: "action",
    label: "指向",
    description: "伸手指前方",
    preview: "👉",
    promptFragment: "pointing forward with one hand",
    structured: { action: "伸手指前方" },
    tags: ["互動"],
  },
  {
    id: "action.sitting",
    family: "action",
    label: "坐下",
    description: "坐姿",
    preview: "🪑",
    promptFragment: "sitting down, calm posture",
    structured: { action: "坐下" },
    tags: ["靜態"],
  },
  {
    id: "action.reaching",
    family: "action",
    label: "伸手",
    description: "向前伸手",
    preview: "🤚",
    promptFragment: "reaching out with one hand",
    structured: { action: "向前伸手" },
    tags: ["互動"],
  },
  {
    id: "action.thinking",
    family: "action",
    label: "思考姿",
    description: "手托腮或沉思",
    preview: "🤔",
    promptFragment: "in a thoughtful pose, hand near chin",
    structured: { action: "思考姿，略托腮" },
    tags: ["情緒", "靜態"],
  },
  {
    id: "action.reacting",
    family: "action",
    label: "反應",
    description: "身體微微後退或驚起",
    preview: "⚡",
    promptFragment: "reacting with a slight body movement",
    structured: { action: "身體微微反應" },
    tags: ["情緒", "動態"],
  },
  {
    id: "action.crouching",
    family: "action",
    label: "蹲下",
    description: "低姿",
    preview: "🧎",
    promptFragment: "crouching low",
    structured: { action: "蹲下" },
    tags: ["靜態"],
  },
];

const expressionPresets: VisualChoicePreset[] = [
  {
    id: "expression.neutral",
    family: "expression",
    label: "平靜",
    preview: "😐",
    promptFragment: "neutral calm expression",
    structured: { performance: { emotion: "平靜" } },
    tags: ["基礎"],
  },
  {
    id: "expression.smile",
    family: "expression",
    label: "微笑",
    preview: "🙂",
    promptFragment: "gentle smile",
    structured: { performance: { emotion: "微笑" } },
    tags: ["正面"],
  },
  {
    id: "expression.happy",
    family: "expression",
    label: "開心",
    preview: "😄",
    promptFragment: "happy, bright expression",
    structured: { performance: { emotion: "開心" } },
    tags: ["正面"],
  },
  {
    id: "expression.surprised",
    family: "expression",
    label: "驚訝",
    preview: "😮",
    promptFragment: "surprised expression, eyes slightly widened",
    structured: { performance: { emotion: "驚訝" } },
    tags: ["強烈"],
  },
  {
    id: "expression.worried",
    family: "expression",
    label: "擔心",
    preview: "😟",
    promptFragment: "worried, concerned expression",
    structured: { performance: { emotion: "擔心" } },
    tags: ["負面"],
  },
  {
    id: "expression.determined",
    family: "expression",
    label: "堅定",
    preview: "😤",
    promptFragment: "determined, resolute expression",
    structured: { performance: { emotion: "堅定" } },
    tags: ["正面"],
  },
  {
    id: "expression.sad",
    family: "expression",
    label: "悲傷",
    preview: "😢",
    promptFragment: "sad, downcast expression",
    structured: { performance: { emotion: "悲傷" } },
    tags: ["負面"],
  },
  {
    id: "expression.angry",
    family: "expression",
    label: "生氣",
    preview: "😠",
    promptFragment: "angry expression",
    structured: { performance: { emotion: "生氣" } },
    tags: ["強烈"],
  },
  {
    id: "expression.focused",
    family: "expression",
    label: "專注",
    preview: "🧐",
    promptFragment: "focused, attentive expression",
    structured: { performance: { emotion: "專注" } },
    tags: ["基礎"],
  },
  {
    id: "expression.shy",
    family: "expression",
    label: "害羞",
    preview: "😳",
    promptFragment: "shy, slightly embarrassed expression",
    structured: { performance: { emotion: "害羞" } },
    tags: ["情緒"],
  },
];

const cameraPresets: VisualChoicePreset[] = [
  {
    id: "camera.wide",
    family: "camera",
    label: "遠景",
    description: "環境與人物同框",
    preview: "🏞️",
    promptFragment: "wide shot, environment visible",
    structured: { camera: { shotSize: "遠景" } },
    tags: ["鏡別"],
  },
  {
    id: "camera.full",
    family: "camera",
    label: "全景",
    description: "全身",
    preview: "🧍",
    promptFragment: "full shot, full body visible",
    structured: { camera: { shotSize: "全景" } },
    tags: ["鏡別"],
  },
  {
    id: "camera.medium",
    family: "camera",
    label: "中景",
    description: "腰部以上",
    preview: "📷",
    promptFragment: "medium shot",
    structured: { camera: { shotSize: "中景" } },
    tags: ["鏡別"],
  },
  {
    id: "camera.close",
    family: "camera",
    label: "特寫",
    description: "臉部與情緒",
    preview: "🔍",
    promptFragment: "close-up shot, focus on face",
    structured: { camera: { shotSize: "特寫" } },
    tags: ["鏡別"],
  },
  {
    id: "camera.extreme_close",
    family: "camera",
    label: "大特寫",
    description: "眼睛或細節",
    preview: "👁️",
    promptFragment: "extreme close-up",
    structured: { camera: { shotSize: "大特寫" } },
    tags: ["鏡別"],
  },
  {
    id: "camera.low_angle",
    family: "camera",
    label: "低角度",
    description: "仰拍，顯得高大",
    preview: "⬆️",
    promptFragment: "low angle shot, looking up",
    structured: { camera: { angle: "低角度" } },
    tags: ["角度"],
  },
  {
    id: "camera.high_angle",
    family: "camera",
    label: "高角度",
    description: "俯拍",
    preview: "⬇️",
    promptFragment: "high angle shot, looking down",
    structured: { camera: { angle: "高角度" } },
    tags: ["角度"],
  },
  {
    id: "camera.eye_level",
    family: "camera",
    label: "平視",
    description: "與視線齊平",
    preview: "➡️",
    promptFragment: "eye-level shot",
    structured: { camera: { angle: "平視" } },
    tags: ["角度"],
  },
  {
    id: "camera.over_shoulder",
    family: "camera",
    label: "過肩",
    description: "從角色肩後看",
    preview: "👤",
    promptFragment: "over-the-shoulder shot",
    structured: { camera: { angle: "過肩" } },
    tags: ["角度"],
  },
  {
    id: "camera.slow_push",
    family: "camera",
    label: "緩推",
    description: "鏡頭緩慢靠近",
    preview: "➡️🔍",
    promptFragment: "slow push-in camera movement",
    structured: { camera: { movement: "緩推" } },
    tags: ["運鏡"],
  },
  {
    id: "camera.static",
    family: "camera",
    label: "固定",
    description: "鏡頭不動",
    preview: "📌",
    promptFragment: "static locked-off camera",
    structured: { camera: { movement: "固定" } },
    tags: ["運鏡"],
  },
];

const lightingPresets: VisualChoicePreset[] = [
  {
    id: "lighting.morning_soft",
    family: "lighting",
    label: "清晨柔光",
    description: "溫柔晨光",
    preview: "🌅",
    promptFragment: "soft morning light, gentle warmth",
    structured: { camera: { lighting: "清晨柔光" } },
    tags: ["日間"],
  },
  {
    id: "lighting.daylight",
    family: "lighting",
    label: "日間",
    description: "自然日光",
    preview: "☀️",
    promptFragment: "natural daylight",
    structured: { camera: { lighting: "日間自然光" } },
    tags: ["日間"],
  },
  {
    id: "lighting.overcast",
    family: "lighting",
    label: "陰天",
    description: "柔和漫射",
    preview: "☁️",
    promptFragment: "overcast soft diffused light",
    structured: { camera: { lighting: "陰天柔光" } },
    tags: ["日間"],
  },
  {
    id: "lighting.golden_hour",
    family: "lighting",
    label: "黃昏逆光",
    description: "金色邊緣光",
    preview: "🌇",
    promptFragment: "golden hour backlight, warm rim light",
    structured: { camera: { lighting: "黃昏逆光" } },
    tags: ["黃昏"],
  },
  {
    id: "lighting.blue_hour",
    family: "lighting",
    label: "藍調時刻",
    description: "暮色藍光",
    preview: "🌆",
    promptFragment: "blue hour cool twilight light",
    structured: { camera: { lighting: "藍調時刻" } },
    tags: ["黃昏"],
  },
  {
    id: "lighting.night",
    family: "lighting",
    label: "夜晚",
    description: "夜景或月光",
    preview: "🌙",
    promptFragment: "night lighting, moonlit or city lights",
    structured: { camera: { lighting: "夜晚" } },
    tags: ["夜間"],
  },
  {
    id: "lighting.rainy",
    family: "lighting",
    label: "雨天",
    description: "濕潤反射",
    preview: "🌧️",
    promptFragment: "rainy atmosphere, wet reflections",
    structured: { camera: { lighting: "雨天" } },
    tags: ["天氣"],
  },
  {
    id: "lighting.warm_indoor",
    family: "lighting",
    label: "室內暖光",
    description: "燈火溫暖",
    preview: "💡",
    promptFragment: "warm indoor practical lighting",
    structured: { camera: { lighting: "室內暖光" } },
    tags: ["室內"],
  },
  {
    id: "lighting.cool_indoor",
    family: "lighting",
    label: "室內冷光",
    description: "偏冷人工光",
    preview: "🧊",
    promptFragment: "cool indoor lighting",
    structured: { camera: { lighting: "室內冷光" } },
    tags: ["室內"],
  },
  {
    id: "lighting.foggy",
    family: "lighting",
    label: "霧氣",
    description: "朦朧大氣",
    preview: "🌫️",
    promptFragment: "foggy soft atmospheric light",
    structured: { camera: { lighting: "霧氣" } },
    tags: ["天氣"],
  },
];

const stylePresets: VisualChoicePreset[] = [
  {
    id: "style.healing_picturebook",
    family: "style",
    label: "治癒繪本風",
    description: "柔和插畫、溫暖色調",
    preview: "📖",
    promptFragment: "healing picture-book illustration style, soft colors, gentle lines",
    structured: { styleHint: "治癒繪本風" },
    tags: ["插畫"],
  },
  {
    id: "style.cinematic_anime",
    family: "style",
    label: "電影感動畫",
    description: "有電影感的動畫質感",
    preview: "🎬",
    promptFragment: "cinematic anime style, filmic lighting and composition",
    structured: { styleHint: "電影感動畫" },
    tags: ["動畫"],
  },
  {
    id: "style.soft_watercolor",
    family: "style",
    label: "柔和水彩",
    description: "水彩暈染",
    preview: "🎨",
    promptFragment: "soft watercolor style, gentle washes",
    structured: { styleHint: "柔和水彩" },
    tags: ["插畫"],
  },
  {
    id: "style.graphic_manga",
    family: "style",
    label: "圖像漫畫",
    description: "清晰線條、漫畫分鏡感",
    preview: "🗯️",
    promptFragment: "graphic manga style, clean lines",
    structured: { styleHint: "圖像漫畫" },
    tags: ["漫畫"],
  },
  {
    id: "style.realistic_film",
    family: "style",
    label: "寫實電影",
    description: "偏寫實的電影畫面",
    preview: "🎥",
    promptFragment: "realistic cinematic film look",
    structured: { styleHint: "寫實電影" },
    tags: ["寫實"],
  },
  {
    id: "style.rough_storyboard",
    family: "style",
    label: "粗略分鏡",
    description: "快速示意、不求精緻",
    preview: "✏️",
    promptFragment: "rough storyboard sketch style, quick indication",
    structured: { styleHint: "粗略分鏡" },
    tags: ["分鏡"],
  },
  {
    id: "style.dreamy_softfocus",
    family: "style",
    label: "柔焦夢境",
    description: "柔焦、夢幻",
    preview: "✨",
    promptFragment: "dreamy soft-focus atmosphere",
    structured: { styleHint: "柔焦夢境" },
    tags: ["氛圍"],
  },
  {
    id: "style.high_contrast",
    family: "style",
    label: "高對比",
    description: "明暗對比強烈",
    preview: "⬛",
    promptFragment: "high contrast dramatic lighting",
    structured: { styleHint: "高對比" },
    tags: ["氛圍"],
  },
];

/** All developer-seeded presets for the current pack version. */
export const VISUAL_CHOICE_PRESETS: VisualChoicePreset[] = [
  ...actionPresets,
  ...expressionPresets,
  ...cameraPresets,
  ...lightingPresets,
  ...stylePresets,
];

export const VISUAL_CHOICE_MANIFEST: VisualChoiceManifest = {
  version: VISUAL_CHOICE_MANIFEST_VERSION,
  presets: VISUAL_CHOICE_PRESETS,
};

/** Convenience re-exports for consumers. */
export {
  listPresetsByFamily,
  findPresetById,
  mapPresetToShotPatch,
  VISUAL_CHOICE_FAMILY_LABEL,
  type VisualChoiceFamily,
  type VisualChoicePreset,
} from "./visualChoiceTypes";
