import { describe, expect, it, vi } from "vitest";
import { z } from "zod";
import { AGENT_SKILLS, BudgetExceededError, InMemoryRunLedger, PracticalAutonomyRuntime, ProviderCircuitBreaker, ToolRegistry, boundedDelegate, type DurableRun } from "./practicalAutonomy";

function run(overrides: Partial<DurableRun> = {}): DurableRun { return { id: "run-1", goalId: "goal-1", planRevision: 1, status: "running", budgetPoints: 100, reservedPoints: 0, actualPoints: 0, updatedAt: new Date().toISOString(), steps: [{ id: "step-1", toolId: "write", input: { value: "ok" }, dependsOn: [], status: "pending", idempotencyKey: "run-1:step-1", attemptCount: 0, reservedPoints: 0, actualPoints: 0 }], ...overrides }; }
function registry(handler: () => Promise<any>, estimate = 10) { return new ToolRegistry().register({ id: "write", label: "Write", category: "project", access: "WRITE", input: z.object({ value: z.string() }), output: z.object({ id: z.string() }), requiredContext: ["userId", "groupId", "projectId"], risk: "medium", confirmation: "never", idempotency: "effect_receipt", cost: { paid: true, estimatePoints: () => estimate }, retry: { maxAttempts: 3, baseDelayMs: 1, allowProviderFallback: true }, verify: (result) => result.verified, evidenceScope: "project", availability: () => ({ available: true }), handlerIdentity: "test.write", handler }); }
const actor = { userId: "u", groupId: "g", projectId: "p" };

describe("PracticalAutonomyRuntime", () => {
  it("retries safely and reserves/settles cost only once", async () => { const ledger = new InMemoryRunLedger(); await ledger.save(run()); let calls = 0; const handler = vi.fn(async () => { calls++; if (calls === 1) throw new Error("temporary"); return { value: { id: "effect-1" }, evidence: [{ type: "effect", ref: "effect-1", verifiedAt: new Date().toISOString() }], actualPoints: 8, verified: true }; }); const runtime = new PracticalAutonomyRuntime(registry(handler), ledger); await runtime.executeStep("run-1", "step-1", actor); await runtime.executeStep("run-1", "step-1", actor); const saved = await ledger.load("run-1"); expect(handler).toHaveBeenCalledTimes(2); expect(saved?.actualPoints).toBe(8); expect(saved?.reservedPoints).toBe(0); });
  it("never completes an unverified write", async () => { const ledger = new InMemoryRunLedger(); await ledger.save(run()); const runtime = new PracticalAutonomyRuntime(registry(async () => ({ value: { id: "x" }, evidence: [], actualPoints: 1, verified: false })), ledger); await expect(runtime.executeStep("run-1", "step-1", actor)).rejects.toThrow("UNVERIFIED_EFFECT"); expect((await ledger.load("run-1"))?.steps[0].status).toBe("failed"); });
  it("does not replay a verified step after recovery", async () => { const ledger = new InMemoryRunLedger(); const handler = vi.fn(async () => ({ value: { id: "x" }, evidence: [{ type: "effect", ref: "x", verifiedAt: new Date().toISOString() }], actualPoints: 3, verified: true })); await ledger.save(run()); await new PracticalAutonomyRuntime(registry(handler), ledger).executeStep("run-1", "step-1", actor); await new PracticalAutonomyRuntime(registry(handler), ledger).executeStep("run-1", "step-1", actor); expect(handler).toHaveBeenCalledOnce(); });
  it("settles a verified crash receipt without replaying the effect", async () => { const ledger = new InMemoryRunLedger(); const persisted = run(); persisted.steps[0].reservedPoints = 10; persisted.reservedPoints = 10; await ledger.save(persisted); await ledger.saveEffect("run-1:step-1", { value: { id: "already-written" }, evidence: [{ type: "effect", ref: "already-written", verifiedAt: new Date().toISOString() }], actualPoints: 7, verified: true }); const handler = vi.fn(); await new PracticalAutonomyRuntime(registry(handler), ledger).executeStep("run-1", "step-1", actor); const recovered = await ledger.load("run-1"); expect(handler).not.toHaveBeenCalled(); expect(recovered?.actualPoints).toBe(7); expect(recovered?.reservedPoints).toBe(0); });
  it("enforces the hard budget before paid work", async () => { const ledger = new InMemoryRunLedger(); const handler = vi.fn(); await ledger.save(run({ budgetPoints: 5 })); await expect(new PracticalAutonomyRuntime(registry(handler, 10), ledger).executeStep("run-1", "step-1", actor)).rejects.toBeInstanceOf(BudgetExceededError); expect(handler).not.toHaveBeenCalled(); });
  it("implements strict pause resume and terminal stop", async () => { const ledger = new InMemoryRunLedger(); await ledger.save(run()); const runtime = new PracticalAutonomyRuntime(registry(vi.fn()), ledger); expect((await runtime.transition("run-1", "pause")).steps[0].status).toBe("paused"); expect((await runtime.transition("run-1", "resume")).steps[0].status).toBe("pending"); expect((await runtime.transition("run-1", "stop")).status).toBe("stopped"); await expect(runtime.transition("run-1", "resume")).rejects.toThrow("INVALID_TRANSITION"); });
});

describe("registry, skills and delegation", () => {
  it("rejects unkeyed writes and duplicate tool truth", () => { const base: any = { id: "x", label: "x", category: "project", access: "WRITE", input: z.object({}), output: z.object({}), requiredContext: [], risk: "low", confirmation: "never", idempotency: "none", cost: { paid: false, estimatePoints: () => 0 }, retry: { maxAttempts: 1, baseDelayMs: 1, allowProviderFallback: false }, verify: () => true, evidenceScope: "project", availability: () => ({ available: true }), handlerIdentity: "x", handler: vi.fn() }; expect(() => new ToolRegistry().register(base)).toThrow("must declare idempotency"); });
  it("ships typed resumable creator skills", () => { expect(AGENT_SKILLS.map((skill) => skill.id)).toEqual(expect.arrayContaining(["project_health_scan", "story_to_storyboard", "creator_delivery_check"])); expect(AGENT_SKILLS.every((skill) => skill.resumable)).toBe(true); });
  it("bounds parallel children and propagates cancellation", async () => { let active = 0, peak = 0; const values = await boundedDelegate([1,2,3,4,5], async (item) => { active++; peak = Math.max(peak, active); await Promise.resolve(); active--; return item * 2; }, { concurrency: 99, maxConcurrency: 2 }); expect(peak).toBeLessThanOrEqual(2); expect(values).toEqual([2,4,6,8,10]); });
  it("opens and recovers provider circuits", () => { let now = 0; const circuit = new ProviderCircuitBreaker(2, 100, () => now); circuit.failure("p"); expect(circuit.available("p")).toBe(true); circuit.failure("p"); expect(circuit.available("p")).toBe(false); now = 101; expect(circuit.available("p")).toBe(true); });
});
